insert into instrument (instrument , brand, rented) values ('guitar', 'Yamaha', false);
insert into instrument (instrument , brand, rented) values ('guitar', 'Roland', false);
insert into instrument (instrument , brand, rented) values ('harmonica', 'Roland', false);
insert into instrument (instrument , brand, rented) values ('violin', 'Yamaha', true);
insert into instrument (instrument , brand, rented) values ('cello', 'Shure', true);
insert into instrument (instrument , brand, rented) values ('violin', 'Gibson', false);
insert into instrument (instrument , brand, rented) values ('trumpet', 'Harman Professional', true);
insert into instrument (instrument , brand, rented) values ('trumpet', 'Shure', false);
insert into instrument (instrument , brand, rented) values ('guitar', 'Shure', true);
insert into instrument (instrument , brand, rented) values ('clarinett', 'Yamaha', true);
insert into instrument (instrument , brand, rented) values ('double bass', 'Fender Musical', true);
insert into instrument (instrument , brand, rented) values ('guitar', 'Fender Musical', true);
insert into instrument (instrument , brand, rented) values ('violin', 'Yamaha', true);
insert into instrument (instrument , brand, rented) values ('guitar', 'Sennheiser', false);
insert into instrument (instrument , brand, rented) values ('guitar', 'Gibson', false);
insert into instrument (instrument , brand, rented) values ('fiol', 'Harman Professional', false);
insert into instrument (instrument , brand, rented) values ('violin', 'Roland', false);
insert into instrument (instrument , brand, rented) values ('violin', 'Fender Musical', false);
insert into instrument (instrument , brand, rented) values ('violin', 'Roland', false);
insert into instrument (instrument , brand, rented) values ('double bass', 'Shure', false);
insert into instrument (instrument , brand, rented) values ('cello', 'Fender Musical', false);
insert into instrument (instrument , brand, rented) values ('clarinett', 'Yamaha', true);
insert into instrument (instrument , brand, rented) values ('clarinett', 'Sennheiser', false);
insert into instrument (instrument , brand, rented) values ('harmonica', 'Sennheiser', false);
insert into instrument (instrument , brand, rented) values ('piano', 'Shure', true);
insert into instrument (instrument , brand, rented) values ('saxophone', 'Yamaha', false);
insert into instrument (instrument , brand, rented) values ('piano', 'Fender Musical', true);
insert into instrument (instrument , brand, rented) values ('guitar', 'Harman Professional', true);
insert into instrument (instrument , brand, rented) values ('clarinett', 'Shure', false);
insert into instrument (instrument , brand, rented) values ('double bass', 'Yamaha', false);

insert into price (type, level, price ) values ('group', 'beginner', 200);
insert into price (type, level, price ) values ('group', 'intermediate', 300);
insert into price (type, level, price ) values ('group', 'advanced', 400);
insert into price (type, level, price ) values ('ensamble', NULL, 100);
insert into price (type, level, price ) values ('individual', NULL, 500);

insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('7237539132', 'Emmi', 'Redsull', 'eredsull0@ucla.edu', '5759621894', '5212 Graceland Avenue', 'Perth', 64160);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('1901616037', 'Fabe', 'Rasper', 'frasper1@dagondesign.com', '9521262797', '54716 Fisk Junction', 'Wichit', 77188);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('2640036998', 'Cindie', 'Flaverty', 'cflaverty2@wikispaces.com', '1707798829', '3304 Westport Center', 'Longtan', 93397);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('6273393680', 'Andriette', 'Smeuin', 'asmeuin3@hud.gov', '5568726614', '02 Namekagon Junction', 'San Carlos de Bariloche', 18193);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('6700470072', 'Iris', 'Parnall', 'iparnall4@pagesperso-orange.fr', '6643239451', '12 Gulseth Center', 'Caseros', 87636);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('9281880571', 'Harold', 'Newark', 'hnewark5@auda.org.au', '9123573704', '478 Gale Park', 'Benhao', 62099);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('1930808992', 'Bird', 'Matoshin', 'bmatoshin6@dagondesign.com', '9979609776', '5939 Aberg Crossing', 'Qiawan', 42644);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('1023323788', 'Sarge', 'Sieb', 'ssieb7@usda.gov', '7341228355', '1447 Northwestern Pass', 'Shuanglong', 47865);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('6243159213', 'Ralf', 'Ronan', 'rronan8@uiuc.edu', '8841759240', '8 Pankratz Plaza', 'Itapecuru Mirim', 94330);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('9402224955', 'Minni', 'O''Keeffe', 'mokeeffe9@altervista.org', '2457578562', '9494 Kedzie Lane', 'Bayshint', 37550);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('4809180409', 'Lee', 'Fley', 'lfleya@home.pl', '6073071745', '82577 Oakridge Way', 'Tuusniemi', 78349);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('2156131147', 'Kylila', 'Burndred', 'kburndredb@icq.com', '3634779495', '3 Elgar Drive', 'Handegate', 87678);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('0378391933', 'Wynn', 'Zoephel', 'wzoephelc@webnode.com', '9686083674', '82 Elmside Park', 'Novopodrezkovo', 85449);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('4848019400', 'Tedda', 'Jakubowski', 'tjakubowskid@cnet.com', '1746531525', '46208 Memorial Junction', 'Wajir', 68854);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('7299432641', 'Verla', 'Dyble', 'vdyblee@bloglines.com', '5244909241', '200 Burrows Trail', 'Novyy Oskol', 60925);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('3313701213', 'Brett', 'Aloshkin', 'baloshkinf@gravatar.com', '7075706522', '2 Carberry Drive', 'Beloha', 10064);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('4401309308', 'Marlie', 'Garrettson', 'mgarrettsong@narod.ru', '1382417111', '0699 Harbort Plaza', 'Reforma', 90961);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('3944941535', 'Alaric', 'Shellcross', 'ashellcrossh@cbslocal.com', '6676282255', '391 Dayton Way', 'Brits', 39718);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('9626213337', 'Dasie', 'Casebourne', 'dcasebournei@webs.com', '2495523905', '224 Ramsey Crossing', 'Rio Piracicaba', 10965);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('6577919135', 'Baily', 'Bellord', 'bbellordj@myspace.com', '7354387900', '87095 Reinke Point', 'Fuzhiping', 79306);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('6487076589', 'Caprice', 'Gallear', 'cgalleark@t-online.de', '3872768497', '9334 Alpine Crossing', 'Antsiranana', 82679);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('4373807930', 'Fons', 'Gadeaux', 'fgadeauxl@comsenz.com', '7272747087', '958 Shoshone Park', 'Cuauhtemoc', 88749);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('1301675385', 'Jyoti', 'Wotton', 'jwottonm@aol.com', '1203940839', '43 Waxwing Lane', 'Yudong', 44941);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('6925943431', 'Shanan', 'Iowarch', 'siowarchn@umn.edu', '5047624205', '242 South Crossing', 'Jawa', 40755);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('3875991249', 'Jayme', 'Stirland', 'jstirlando@netvibes.com', '7319424209', '5003 Kim Road', 'Jiuxian', 42054);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('1698416407', 'Nance', 'Ojeda', 'nojedap@cargocollective.com', '5604485167', '3 Hoffman Center', 'Kulonkali', 15411);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('3940761087', 'Joella', 'Storer', 'jstorerq@ed.gov', '2461234495', '289 Montana Circle', 'Dumingag', 55978);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('5554145760', 'Leonerd', 'Menis', 'lmenisr@google.cn', '8591072890', '9466 Waywood Avenue', 'Vale de São Cosme', 13338);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('9281780135', 'Dedie', 'Byass', 'dbyasss@amazon.co.jp', '3659678094', '859 Crowley Court', 'Telsiai', 61018);
insert into student (person_number, first_name, sur_name, email, phone, street, city , zip) values ('8900267833', 'Anson', 'Quiney', 'aquineyt@elpais.com', '7948134019', '3 Mockingbird Center', 'Jiazhi', 50720);